### ISSUE TITLE
So...what's the plan?

### ISSUE THREAD

**Issue by Valleriite** [taeko-chan/backtimize#1]
What is this mod planned to do,
or is it discontinued?

**Comment by taeko-chan** [comment]
and friend and i wanted to start this project which essentially would tweak the backend of minecraft to improve server performance. originally we wanted to start with an updated path-finding algorithm for mobs.
i'm not sure if we'll end up doing it because we both are working on a lot outside of this right now.

**Comment by Valleriite** [comment]
Thank you,
have a nice day.
